
language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode14.2
  - os: linux
    dist: focal
    services: docker
    arch: amd64
  - os: linux
    dist: focal
    services: docker
    arch: arm64

#before_install:

#install:


script:
  - |
    mkdir -p build;
    cd build;
    cmake -DCMAKE_BUILD_TYPE=RELEASE ..;
    cmake --build . -- -j 2;
    ctest;

#before_deploy:

#deploy:


