
language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode14.2
  - os: linux
    dist: focal
    services: docker
    arch: amd64
  - os: linux
    dist: focal
    services: docker
    arch: arm64

addons:
  homebrew:
    update: false

#https://github.com/travis-ci/travis-ci/issues/6893
if: tag IS present

#https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
git:
  depth: 3
  submodules: false

#before_install:

#install:


script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      bash ./scripts/build_docker_manylinux2014.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      bash ./scripts/build_macos.sh;
    fi

#before_deploy:

#deploy:


