# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
image: Visual Studio 2022

branches:
  except:
    - main

#branches:
# whitelist
#only:
#  - main

# Do not build on tags (GitHub only)
#skip_tags: true
skip_non_tags: true

# Skipping commits with particular message or from user
#skip_commits:
#  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message
#  author: John        # Commit author's username, name, email or regexp maching one of these.

# scripts that are called at very beginning, before repo cloning
init:
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\pyadms

matrix:
  allow_failures:
    - platform: x64
      configuration: Release


# scripts that run after cloning repository
# TODO: best place for bison/flex
install:
  - appveyor DownloadFile https://cygwin.com/setup-x86.exe
  - setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P bison -P flex

# to add several platforms to build matrix:
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


# scripts to run before build
before_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - scripts\build_vs.bat

# to run your custom scripts instead of automatic tests
# test_script:
#   - cd %APPVEYOR_BUILD_FOLDER%\build
#   - SET CTEST_OUTPUT_ON_FAILURE=1
#   - ctest -C Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: *.whl

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: 2izP48RTHHbIC85OpS2qrBrddvOhGl0cwdacXO+rxdFgfKudYpwDtpuzoIliKdBm
    #artifact: dist\*.zip
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true      # deploy on tag push only
      #branch: main                # release from main branch only

